loginTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('accounts.urls')), # Add
]

tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

tasks/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # Se establece en la fecha y hora actuales cuando se crea
    updated_at = models.DateTimeField(auto_now=True)      # Se actualiza en la fecha y hora actuales cada vez que se guarda

    def __str__(self):
        return f'{self.title}, {self.content}'

tasks/forms.py
from django import forms


class TaskCreationForm(forms.Form):
    title = forms.CharField(label='Título', max_length=255)  
    content = forms.CharField(label='Contenido', widget=forms.Textarea())  

tasks/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Task
from .forms import TaskCreationForm
from django.contrib.auth.decorators import login_required    # Añadido

@login_required    # Añadido
def create(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('blog:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)

def index(request):
    tasks = Task.objects.all()
    params = {
        'tasks': tasks,
    }
    return render(request, 'tasks/index.html', params)


def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('tasks:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)


def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    params = {
        'task': task,
    }
    return render(request, 'tasks/detail.html', params)


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.title = request.POST['title']
        task.content = request.POST['content']
        task.save()
        return redirect('tasks:detail', task_id)
    else:
        form = TaskCreationForm(initial={
            'title': task.title,
            'content': task.content,
        })
        params = {
            'task': task,
            'form': form,
        }
        return render(request, 'tasks/edit.html', params)


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.delete()
        return redirect('tasks:index')
    else:
        params = {
            'task': task,
        }
        return render(request, 'tasks/delete.html', params)

tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Registro de Tareas</h1>
<form action="{% url 'tasks:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Registrar">
</form>

<br>

<a href="{% url 'tasks:index' %}">Volver</a>
{% endblock %}

tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Eliminación de Tareas</h1>
<p>
  <strong>Título:</strong>
  {{task.title}}
</p>

<p>
  <strong>Contenido:</strong>
  {{task.content}}
</p>
<form action="{% url 'tasks:delete' task.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Eliminar">
</form>

<br>

<a href="{% url 'tasks:index' %}">Volver</a>
{% endblock %}

tasks/templates/tasks/detail.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Detalles de la Tarea</h1>
<p>
  <strong>Título:</strong>
  {{task.title}}
</p>

<p>
  <strong>Contenido:</strong>
  {{task.content}}
</p>
<a href="{% url 'tasks:index' %}">Volver</a> |
<a href="{% url 'tasks:edit' task.id %}">Editar</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block main %}
<h1>Página de Edición de Tareas</h1>
<form action="{% url 'tasks:edit' task.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Actualizar">
</form>

<br>

<a href="{% url 'tasks:detail' task.id %}">Detalles</a> |
<a href="{% url 'tasks:index' %}">Volver</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block main %}
<h1>Lista de Tareas</h1>
<table>
  <tr>
    <th>Título</th>
    <th>Contenido</th>
    <th colspan="3"></th>
  </tr>
  {% for task in tasks %}
  <tr>
    <td>{{task.title}}</td>
    <td>{{task.content}}</td>
    <td><a href="{% url 'tasks:detail' task.id %}">Detalles</a></td>
    <td><a href="{% url 'tasks:edit' task.id %}">Editar</a></td>
    <td><a href="{% url 'tasks:delete' task.id %}">Eliminar</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'tasks:create' %}">Crear Nuevo</a>

{% endblock %}